version: '3.1'
services:
  local-postgres:
    ports:
      - "5432:5432"
    image: srimani/postgres:v1.0
    restart: always
    volumes:
      - $HOME/.cache/docker/vol/postgres:/var/lib/postgresql/data
    network_mode: bridge